on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: ["1.22", "1.21", "1.20", "1.19"] # keep in sync with go.mod and test/go.mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: Test
        run: make
      - name: go-test
        run: cd test && go test -race -cover -covermode=atomic
      - name: install-test
        run: go install && cd test && go-testcov
      - name: vet
        run: go vet && [ -z "`go fmt`" ]
