on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: ["1.19", "1.18", "1.17"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: Test
        run: cd test && go test -race -cover -covermode=atomic && cd .. && go install && cd test && go-testcov && cd .. && go vet && [ -z "`go fmt`" ]
